import requests

url = "http://localhost:8111/campaign/"

payload = {'account': 'Demo client account - 1',
           'action': 'create',
           'auto_propagate_audience_updates': False,
           'budget': 3324231,
           'campaign': [{'action': 'create',
                         'adset': [{'action': 'create',
                                    'ad': [{'action': 'create',
                                            'adset_id': 'f557bdab-6a98-42fc-8423-db85679d1c7c',
                                            'external_id': 'AD-0049',
                                            'id': '815450f6-b50c-4ca2-bc30-d5c96107fff7',
                                            'is_favorite': False,
                                            'last_state': 'APPROVED',
                                            'name': 'Ad 1 - 300x250',
                                            'platforms': {'facebook': {'action': 'create',
                                                                       'status': 'start',
                                                                       'template': [{'ad_format': 'IMAGE_AD',
                                                                                     'ad_id': '815450f6-b50c-4ca2-bc30-d5c96107fff7',
                                                                                     'asset_ids': ['facebook_2_nelson_-_social_-_adset_1300x250'],
                                                                                     'asset_url': 'https://dummyimage.com/250x250',
                                                                                     'description': 'Description for Get 10% off on Electronics',
                                                                                     'headline': 'dummy offer',
                                                                                     'id': '4d39cebb-af18-45a2-b2c1-0e95ee2417da',
                                                                                     'last_state': 'APPROVED',
                                                                                     'name': 'facebook Ad - 300x250 Template',
                                                                                     'sub_headline': 'Get 10% off on Electronics',
                                                                                     'url': 'https://alchemy-hotel.gale.agency/'}]}},
                                            'status': 'start'}],
                                    'audience': {'attributes': {'age_groups': [],
                                                                'gender': [],
                                                                'geography': [],
                                                                'income': [],
                                                                'interests': []},
                                                 'audience_id': '85cfce60-b8d9-4000-8b3c-3a5bb66a4b70',
                                                 'id': '85cfce60-b8d9-4000-8b3c-3a5bb66a4b70',
                                                 'open': True,
                                                 'targeted': True},
                                    'budget': 2017476,
                                    'campaign_id': 'd6c61326-191e-4481-a409-8ecae85bc9gh',
                                    'caption': 'dummy offer',
                                    'external_id': 'ADS0084',
                                    'id': 'f557bdab-6a98-42fc-8423-db85679d1c7c',
                                    'is_complete': True,
                                    'is_favorite': False,
                                    'last_state': 'APPROVED',
                                    'mediaplan_objective': 'Awareness',
                                    'name': 'facebook 2 nelson - Social - Adset 1',
                                    'offer': 'Get 10% off on Electronics',
                                    'platforms': {'facebook': {'action': 'create',
                                                               'ad_format': 'RESPONSIVE',
                                                               'ad_rotation': 'Standard',
                                                               'ad_size': ['300x250'],
                                                               'budget': 1296700,
                                                               'id': 'a8c00f81-004a-40e0-b7c8-79146b824fcc',
                                                               'interests': [{'key': '6002988344794',
                                                                              'value': 'Interests >> Additional Interests >> Cricket'}],
                                                               'last_state': 'APPROVED',
                                                               'name': 'facebook',
                                                               'parent_id': 'f557bdab-6a98-42fc-8423-db85679d1c7c',
                                                               'pixel_event': 'CONTENT_VIEW',
                                                               'placement': ['fb_feed'],
                                                               'status': 'start'}},
                                    'schedule': {'end': '2018-06-24', 'start': '2018-06-16'},
                                    'status': 'start'}],
                         'budget': 2017476,
                         'channels': ['social'],
                         'external_id': 'CAM0093',
                         'id': 'd6c61326-191e-4481-a409-8ecae85bc9gh',
                         'is_complete': True,
                         'is_favorite': False,
                         'last_state': 'APPROVED',
                         'mediaplan_id': 'bcc06595-caf7-410c-a2be-cc88f93c4788',
                         'name': 'facebook 2 nelson - Social',
                         'platforms': {'facebook': {'action': 'create',
                                                    'bid_cap': 123.0,
                                                    'bid_strategy': 'IMPRESSIONS',
                                                    'budget': 1296700,
                                                    'delivery_type': 'standard',
                                                    'extensions': [],
                                                    'fb_pixel': '217049922179026',
                                                    'frequency_cap': {'impressions': '234', 'period': 'DAY'},
                                                    'id': 'a69e7509-a897-4d43-ab73-0050cb492561',
                                                    'last_state': 'APPROVED',
                                                    'location': [{'canonical_name': 'India, India',
                                                                  'country_code': 'IN',
                                                                  'country_name': 'India',
                                                                  'include': True,
                                                                  'key': 'IN',
                                                                  'name': 'India',
                                                                  'type': 'country'}],
                                                    'name': 'facebook',
                                                    'parent_id': 'd6c61326-191e-4481-a409-8ecae85bc9gh',
                                                    'status': 'start'}},
                         'schedule': {'end': '2018-06-24', 'start': '2018-06-16'},
                         'status': 'start'}],
           'channel_mix': [{'budget_allocated': 60.69,
                            'channel': 'social',
                            'id': 'd4acbb26-2d51-4e3d-9f0e-c74afe3e5bf3',
                            'mediaplan_id': 'bcc06595-caf7-410c-a2be-cc88f93c4788'}],
           'client': {'name': 'Democlientaccount-1',
                      'site': ['https://alchemy-hotel.gale.agency/']},
           'configuration_profile_id': '2516ba4c-3bbd-4ae4-9f98-2b4be5e525f4',
           'configuration_profile_updation_time': '2017-07-09T10:55:3523',
           'external_id': 'MED0066',
           'id': 'bcc06595-caf7-410c-a2be-cc88f93c4789',
           'initiative': None,
           'initiative_id': None,
           'is_complete': True,
           'is_favorite': False,
           'last_state': 'APPROVED',
           'media_kpis': [{'id': '85a21da9-b975-425a-9745-329a9f04079d',
                           'name': 'Views count',
                           'variables': ['222']}],
           'name': 'facebook 2 nelson',
           'objective': 'awareness',
           'schedule': {'end': '2018-06-24', 'start': '2018-06-16'},
           'segment': [{'caption': 'dummy offer',
                        'id': '4b34a539-9760-456b-a837-418e47a07157',
                        'offer': {'attributes': {'X': '10',
                                                 'amount': '100',
                                                 'currency': 'USD',
                                                 'product': 'Electronics'},
                                  'id': '92130235-3ff3-4366-9b32-08208ca4493b',
                                  'initiative': None,
                                  'initiative_name': None,
                                  'name': 'Summer Offer',
                                  'offer_template_id': 'b377a52c-302f-463f-980d-b7a7a9c4e285',
                                  'prerequisite_ids': ['a09618b1-dfc2-40d9-a7f2-84cfa397a559']},
                        'target_list': {'alchemy_core_list_id': '92d8504f-c5e2-4877-892e-decd69fc9c59',
                                        'attributes': {'age_groups': [], 'gender': [], 'interests': []},
                                        'data': {'size': 43},
                                        'exclusions_list': [],
                                        'id': '39e85ede-cabc-46d1-8af4-609fe558fb29',
                                        'inclusions_list': [{'alchemy_core_list_id': '194b91a1-76cf-41e9-bcb2-36e65016b83a',
                                                             'data': {'age_groups': ['18 - 24',
                                                                                     '25 - 34',
                                                                                     '35 - 44',
                                                                                     '45 - 54',
                                                                                     '55 - 64',
                                                                                     '65 - 100']},
                                                             'id': 'b14f2ed5-ea54-4139-826c-8dc0f3b587fa',
                                                             'name': 'Gale people',
                                                             'type': 'FIRST_PARTY'}],
                                        'mediaplans': [{'id': '41b8ea3f-0fda-4a45-a7cc-66a95a608848',
                                                        'name': 'facebook nelson',
                                                        'schedule': {'end': '2018-06-24T12:00:01Z',
                                                                     'start': '2018-06-16T12:00:00Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': '5d58653b-e381-40a5-bfb9-6cc771b0d6a1',
                                                        'name': 'Nelson',
                                                        'schedule': {'end': '2018-06-24T12:00:01Z',
                                                                     'start': '2018-06-10T12:00:00Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': '94aa7927-54dd-49ca-9977-a3e05eb72f00',
                                                        'name': 'Auto media plan-ss test',
                                                        'schedule': {'end': '2018-06-19T09:47:01Z',
                                                                     'start': '2018-06-09T09:47:50Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': '7fb8632b-01ba-4380-941e-91697ff554a9',
                                                        'name': 'Mail MP',
                                                        'schedule': {'end': '2018-06-15T12:00:01Z',
                                                                     'start': '2018-06-10T12:00:00Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': 'bcc06595-caf7-410c-a2be-cc88f93c4788',
                                                        'name': 'facebook 2 nelson',
                                                        'schedule': {'end': '2018-06-24T12:00:01Z',
                                                                     'start': '2018-06-16T12:00:00Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': '2341a84a-2556-4534-970b-190e4fe9f5a6',
                                                        'name': 'Email 19-4',
                                                        'schedule': {'end': '2018-04-21T00:00:00Z',
                                                                     'start': '2018-04-19T00:00:00Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': 'bcba1748-cb90-40f3-89a8-cc242e01358e',
                                                        'name': '20-4 Test',
                                                        'schedule': {'end': '2018-04-25T00:00:00Z',
                                                                     'start': '2018-04-20T00:00:00Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': '9b83a64b-f097-4fec-8d5c-63c9000025b1',
                                                        'name': 'Budget test Media Plan',
                                                        'schedule': {'end': '2018-04-23T12:00:00Z',
                                                                     'start': '2018-04-20T12:00:00Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': 'b2a17045-d011-4300-a974-68d8290a57ac',
                                                        'name': '19 April test',
                                                        'schedule': {'end': '2018-04-25T00:00:00Z',
                                                                     'start': '2018-04-20T00:00:00Z',
                                                                     'timezone': 'UTC'}},
                                                       {'id': 'a8c5a8cd-af6e-4cef-b398-032d2461b5f7',
                                                        'name': 'nelson faceebook',
                                                        'schedule': {'end': '2018-06-17T12:00:01Z',
                                                                     'start': '2018-06-16T12:00:00Z',
                                                                     'timezone': 'UTC'}}],
                                        'name': 'Gale Blr'}}],
           'status': 'start'}
headers = {
    'Content-Type': "application/json",
    'Cache-Control': "no-cache",
    'Postman-Token': "e83ab86c-2200-4d9e-b4b7-c15931e20547"
}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
